version: '2'
services:
  devnetsuivi-app:
    image: devnetsuivi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://devnetsuivi-postgresql:5432/DevNetSuivi
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8300:8300
  devnetsuivi-postgresql:
    extends:
      file: postgresql.yml
      service: devnetsuivi-postgresql
